Repository lanyanxiang/habits-cli, pull requests merged in 2022-06, with the labels that each got.

#71 [Feature] Standard workflows
  .github/workflows/auto-merge.yml
  .github/workflows/prettier.yml
Labels: enhancement, priority:medium, refactor, v0.3-beta, ready

#74 [Feature] Remove merge delete branch
  .github/workflows/auto-merge.yml
Labels: bug, ready

#75 [Feature] Add CODEOWNERS file
  .github/CODEOWNERS
Labels: documentation, refactor, ready

#76 Feature 3 Added compact table display option
  src/commands/transaction/list.ts
Labels: enhancement, v0.3-beta, ready

#78 Feature/compact table display
  .github/workflows/auto-merge.yml
  src/commands/transaction/list.ts
Labels: enhancement, priority:low, v0.3-beta, ready

#83 [Feature] Refactor compact table code
  src/commands/transaction/list.ts
Labels: enhancement, priority:medium, refactor, v0.3-beta
